# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pr_region_2/pr_region_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2 || ORIG_REF_NAME==pr_region_2} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_xbar_0/pr_region_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_xbar_0 || ORIG_REF_NAME==pr_region_2_xbar_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_axi_interconnect_0_0/pr_region_2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_axi_interconnect_0_0 || ORIG_REF_NAME==pr_region_2_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_xbar_1/pr_region_2_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_xbar_1 || ORIG_REF_NAME==pr_region_2_xbar_1} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_axi_interconnect_1_0/pr_region_2_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_axi_interconnect_1_0 || ORIG_REF_NAME==pr_region_2_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_conv_layer_0_0/pr_region_2_conv_layer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_conv_layer_0_0 || ORIG_REF_NAME==pr_region_2_conv_layer_0_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_fc_layer_0_0/pr_region_2_fc_layer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_fc_layer_0_0 || ORIG_REF_NAME==pr_region_2_fc_layer_0_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_proc_sys_reset_0_0/pr_region_2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_proc_sys_reset_0_0 || ORIG_REF_NAME==pr_region_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_s00_regslice_0/pr_region_2_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_s00_regslice_0 || ORIG_REF_NAME==pr_region_2_s00_regslice_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_auto_us_0/pr_region_2_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_auto_us_0 || ORIG_REF_NAME==pr_region_2_auto_us_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_auto_rs_0/pr_region_2_auto_rs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_auto_rs_0 || ORIG_REF_NAME==pr_region_2_auto_rs_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_auto_rs_w_0/pr_region_2_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_auto_rs_w_0 || ORIG_REF_NAME==pr_region_2_auto_rs_w_0} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_auto_us_1/pr_region_2_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_auto_us_1 || ORIG_REF_NAME==pr_region_2_auto_us_1} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_auto_rs_1/pr_region_2_auto_rs_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_auto_rs_1 || ORIG_REF_NAME==pr_region_2_auto_rs_1} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_auto_rs_w_1/pr_region_2_auto_rs_w_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_auto_rs_w_1 || ORIG_REF_NAME==pr_region_2_auto_rs_w_1} -quiet] -quiet

# IP: bd/pr_region_2/ip/pr_region_2_m00_regslice_0/pr_region_2_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pr_region_2_m00_regslice_0 || ORIG_REF_NAME==pr_region_2_m00_regslice_0} -quiet] -quiet

# XDC: bd/pr_region_2/pr_region_2_ooc.xdc
