# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/ECE1373/lab2/ECE1373_assignment2-2021/8v3_shell/pr_region_test_proj_2/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_fc_layer_0_0/pr_region_2_fc_layer_0_0.xci
# IP: The module: 'pr_region_2_fc_layer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/ECE1373/lab2/ECE1373_assignment2-2021/8v3_shell/pr_region_test_proj_2/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_fc_layer_0_0/constraints/fc_layer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_region_2_fc_layer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Documents/ECE1373/lab2/ECE1373_assignment2-2021/8v3_shell/pr_region_test_proj_2/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_fc_layer_0_0/pr_region_2_fc_layer_0_0.xci
# IP: The module: 'pr_region_2_fc_layer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/ECE1373/lab2/ECE1373_assignment2-2021/8v3_shell/pr_region_test_proj_2/pr_region.srcs/sources_1/bd/pr_region_2/ip/pr_region_2_fc_layer_0_0/constraints/fc_layer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_region_2_fc_layer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
